# Generated by Django 3.2.4 on 2021-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('proj_name', models.CharField(max_length=15)),
                ('proj_description', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Skills',
        ),
    ]
