# Generated by Django 3.2.4 on 2021-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210614_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('prof_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='prof_pic',
        ),
    ]
