# Generated by Django 3.2.4 on 2021-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210614_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='about_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
